[2024-08-06T22:31:20.489+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T22:01:33.346495+00:00 [queued]>
[2024-08-06T22:31:20.494+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T22:01:33.346495+00:00 [queued]>
[2024-08-06T22:31:20.495+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T22:31:20.495+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-08-06T22:31:20.495+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T22:31:20.501+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunOperator): dbt_run> on 2024-08-06 22:01:33.346495+00:00
[2024-08-06T22:31:20.503+0000] {standard_task_runner.py:55} INFO - Started process 52 to run task
[2024-08-06T22:31:20.506+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_parquet_to_bq_dag', 'dbt_run', 'manual__2024-08-06T22:01:33.346495+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/load_dbt_dag.py', '--cfg-path', '/tmp/tmpe7rxz482']
[2024-08-06T22:31:20.507+0000] {standard_task_runner.py:83} INFO - Job 81: Subtask dbt_run
[2024-08-06T22:31:20.539+0000] {task_command.py:388} INFO - Running <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T22:01:33.346495+00:00 [running]> on host cf0df9e834a7
[2024-08-06T22:31:20.566+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=miguel
AIRFLOW_CTX_DAG_ID=load_parquet_to_bq_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-08-06T22:01:33.346495+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-06T22:01:33.346495+00:00
[2024-08-06T22:31:20.566+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/dbt_project --models load_parquet_to_test
[2024-08-06T22:31:20.570+0000] {dbt_hook.py:126} INFO - Output:
[2024-08-06T22:31:21.656+0000] {dbt_hook.py:130} INFO - [0m22:31:21  Running with dbt=1.8.4
[2024-08-06T22:31:22.509+0000] {dbt_hook.py:130} INFO - [0m22:31:22  Registered adapter: bigquery=1.8.2
[2024-08-06T22:31:22.711+0000] {dbt_hook.py:130} INFO - [0m22:31:22  Found 1 model, 1 source, 473 macros
[2024-08-06T22:31:22.712+0000] {dbt_hook.py:130} INFO - [0m22:31:22
[2024-08-06T22:31:24.086+0000] {dbt_hook.py:130} INFO - [0m22:31:24  Concurrency: 1 threads (target='dev')
[2024-08-06T22:31:24.087+0000] {dbt_hook.py:130} INFO - [0m22:31:24
[2024-08-06T22:31:24.092+0000] {dbt_hook.py:130} INFO - [0m22:31:24  1 of 1 START sql table model prazos_project_dataset.load_parquet_to_test ....... [RUN]
[2024-08-06T22:31:25.883+0000] {dbt_hook.py:130} INFO - [0m22:31:25  BigQuery adapter: https://console.cloud.google.com/bigquery?project=prazos-project&j=bq:US:83c21048-3910-44ec-b3c9-103be321a66f&page=queryresults
[2024-08-06T22:31:25.892+0000] {dbt_hook.py:130} INFO - [0m22:31:25  1 of 1 ERROR creating sql table model prazos_project_dataset.load_parquet_to_test  [[31mERROR[0m in 1.80s]
[2024-08-06T22:31:25.894+0000] {dbt_hook.py:130} INFO - [0m22:31:25
[2024-08-06T22:31:25.894+0000] {dbt_hook.py:130} INFO - [0m22:31:25  Finished running 1 table model in 0 hours 0 minutes and 3.18 seconds (3.18s).
[2024-08-06T22:31:25.922+0000] {dbt_hook.py:130} INFO - [0m22:31:25
[2024-08-06T22:31:25.922+0000] {dbt_hook.py:130} INFO - [0m22:31:25  [31mCompleted with 1 error and 0 warnings:[0m
[2024-08-06T22:31:25.923+0000] {dbt_hook.py:130} INFO - [0m22:31:25
[2024-08-06T22:31:25.923+0000] {dbt_hook.py:130} INFO - [0m22:31:25    Database Error in model load_parquet_to_test (models/load_parquet_to_test.sql)
[2024-08-06T22:31:25.923+0000] {dbt_hook.py:130} INFO -   Syntax error: Expected ")" but got ";" at [15:24]
[2024-08-06T22:31:25.923+0000] {dbt_hook.py:130} INFO -   compiled Code at target/run/prazos_project/models/load_parquet_to_test.sql
[2024-08-06T22:31:25.923+0000] {dbt_hook.py:130} INFO - [0m22:31:25
[2024-08-06T22:31:25.924+0000] {dbt_hook.py:130} INFO - [0m22:31:25  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-08-06T22:31:26.763+0000] {dbt_hook.py:132} INFO - Command exited with return code 1
[2024-08-06T22:31:26.769+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2024-08-06T22:31:26.771+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=load_parquet_to_bq_dag, task_id=dbt_run, execution_date=20240806T220133, start_date=20240806T223120, end_date=20240806T223126
[2024-08-06T22:31:26.777+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 81 for task dbt_run (dbt command failed; 52)
[2024-08-06T22:31:26.811+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-06T22:31:26.817+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
