[2024-08-06T21:54:51.595+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T21:49:44.924253+00:00 [queued]>
[2024-08-06T21:54:51.600+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T21:49:44.924253+00:00 [queued]>
[2024-08-06T21:54:51.600+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T21:54:51.600+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-08-06T21:54:51.601+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T21:54:51.606+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunOperator): dbt_run> on 2024-08-06 21:49:44.924253+00:00
[2024-08-06T21:54:51.608+0000] {standard_task_runner.py:55} INFO - Started process 552 to run task
[2024-08-06T21:54:51.610+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_parquet_to_bq_dag', 'dbt_run', 'manual__2024-08-06T21:49:44.924253+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/load_dbt_dag.py', '--cfg-path', '/tmp/tmp9ci4wqef']
[2024-08-06T21:54:51.611+0000] {standard_task_runner.py:83} INFO - Job 67: Subtask dbt_run
[2024-08-06T21:54:51.638+0000] {task_command.py:388} INFO - Running <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T21:49:44.924253+00:00 [running]> on host cf0df9e834a7
[2024-08-06T21:54:51.661+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=miguel
AIRFLOW_CTX_DAG_ID=load_parquet_to_bq_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-08-06T21:49:44.924253+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-06T21:49:44.924253+00:00
[2024-08-06T21:54:51.662+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/dbt_project --models load_parquet_to_test
[2024-08-06T21:54:51.666+0000] {dbt_hook.py:126} INFO - Output:
[2024-08-06T21:54:52.603+0000] {dbt_hook.py:130} INFO - [0m21:54:52  Running with dbt=1.8.4
[2024-08-06T21:54:53.221+0000] {dbt_hook.py:130} INFO - [0m21:54:53  Registered adapter: bigquery=1.8.2
[2024-08-06T21:54:53.475+0000] {dbt_hook.py:130} INFO - [0m21:54:53  Found 1 model, 1 source, 473 macros
[2024-08-06T21:54:53.476+0000] {dbt_hook.py:130} INFO - [0m21:54:53
[2024-08-06T21:54:55.113+0000] {dbt_hook.py:130} INFO - [0m21:54:55
[2024-08-06T21:54:55.113+0000] {dbt_hook.py:130} INFO - [0m21:54:55  Finished running  in 0 hours 0 minutes and 1.64 seconds (1.64s).
[2024-08-06T21:54:55.115+0000] {dbt_hook.py:130} INFO - [0m21:54:55  Encountered an error:
[2024-08-06T21:54:55.116+0000] {dbt_hook.py:130} INFO - Database Error
[2024-08-06T21:54:55.116+0000] {dbt_hook.py:130} INFO -   Invalid project ID 'prazos_project'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
[2024-08-06T21:54:55.969+0000] {dbt_hook.py:132} INFO - Command exited with return code 2
[2024-08-06T21:54:55.978+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2024-08-06T21:54:55.980+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=load_parquet_to_bq_dag, task_id=dbt_run, execution_date=20240806T214944, start_date=20240806T215451, end_date=20240806T215455
[2024-08-06T21:54:55.987+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 67 for task dbt_run (dbt command failed; 552)
[2024-08-06T21:54:56.030+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-06T21:54:56.043+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
