[2024-08-06T21:49:46.254+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T21:49:44.924253+00:00 [queued]>
[2024-08-06T21:49:46.259+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T21:49:44.924253+00:00 [queued]>
[2024-08-06T21:49:46.259+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T21:49:46.259+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-08-06T21:49:46.260+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T21:49:46.264+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunOperator): dbt_run> on 2024-08-06 21:49:44.924253+00:00
[2024-08-06T21:49:46.267+0000] {standard_task_runner.py:55} INFO - Started process 112 to run task
[2024-08-06T21:49:46.269+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_parquet_to_bq_dag', 'dbt_run', 'manual__2024-08-06T21:49:44.924253+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/load_dbt_dag.py', '--cfg-path', '/tmp/tmp03z4rgle']
[2024-08-06T21:49:46.269+0000] {standard_task_runner.py:83} INFO - Job 65: Subtask dbt_run
[2024-08-06T21:49:46.294+0000] {task_command.py:388} INFO - Running <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T21:49:44.924253+00:00 [running]> on host cf0df9e834a7
[2024-08-06T21:49:46.315+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=miguel
AIRFLOW_CTX_DAG_ID=load_parquet_to_bq_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-08-06T21:49:44.924253+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-06T21:49:44.924253+00:00
[2024-08-06T21:49:46.315+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/dbt_project --models load_parquet_to_test
[2024-08-06T21:49:46.319+0000] {dbt_hook.py:126} INFO - Output:
[2024-08-06T21:49:47.170+0000] {dbt_hook.py:130} INFO - [0m21:49:47  Running with dbt=1.8.4
[2024-08-06T21:49:47.717+0000] {dbt_hook.py:130} INFO - [0m21:49:47  Registered adapter: bigquery=1.8.2
[2024-08-06T21:49:47.800+0000] {dbt_hook.py:130} INFO - [0m21:49:47  Unable to do partial parsing because a project config has changed
[2024-08-06T21:49:48.434+0000] {dbt_hook.py:130} INFO - [0m21:49:48  Found 1 model, 1 source, 473 macros
[2024-08-06T21:49:48.435+0000] {dbt_hook.py:130} INFO - [0m21:49:48
[2024-08-06T21:49:50.058+0000] {dbt_hook.py:130} INFO - [0m21:49:50
[2024-08-06T21:49:50.059+0000] {dbt_hook.py:130} INFO - [0m21:49:50  Finished running  in 0 hours 0 minutes and 1.62 seconds (1.62s).
[2024-08-06T21:49:50.061+0000] {dbt_hook.py:130} INFO - [0m21:49:50  Encountered an error:
[2024-08-06T21:49:50.061+0000] {dbt_hook.py:130} INFO - Database Error
[2024-08-06T21:49:50.061+0000] {dbt_hook.py:130} INFO -   Invalid project ID 'prazos_project'. Project IDs must contain 6-63 lowercase letters, digits, or dashes. Some project IDs also include domain name separated by a colon. IDs must start with a letter and may not end with a dash.
[2024-08-06T21:49:50.968+0000] {dbt_hook.py:132} INFO - Command exited with return code 2
[2024-08-06T21:49:50.973+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2024-08-06T21:49:50.975+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=load_parquet_to_bq_dag, task_id=dbt_run, execution_date=20240806T214944, start_date=20240806T214946, end_date=20240806T214950
[2024-08-06T21:49:50.981+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 65 for task dbt_run (dbt command failed; 112)
[2024-08-06T21:49:51.008+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-06T21:49:51.016+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
