[2024-08-06T22:04:45.837+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T22:04:45.034373+00:00 [queued]>
[2024-08-06T22:04:45.854+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T22:04:45.034373+00:00 [queued]>
[2024-08-06T22:04:45.854+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T22:04:45.855+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-08-06T22:04:45.855+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-08-06T22:04:45.862+0000] {taskinstance.py:1300} INFO - Executing <Task(DbtRunOperator): dbt_run> on 2024-08-06 22:04:45.034373+00:00
[2024-08-06T22:04:45.866+0000] {standard_task_runner.py:55} INFO - Started process 127 to run task
[2024-08-06T22:04:45.868+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'load_parquet_to_bq_dag', 'dbt_run', 'manual__2024-08-06T22:04:45.034373+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/load_dbt_dag.py', '--cfg-path', '/tmp/tmp4vejrtux']
[2024-08-06T22:04:45.869+0000] {standard_task_runner.py:83} INFO - Job 77: Subtask dbt_run
[2024-08-06T22:04:45.919+0000] {task_command.py:388} INFO - Running <TaskInstance: load_parquet_to_bq_dag.dbt_run manual__2024-08-06T22:04:45.034373+00:00 [running]> on host cf0df9e834a7
[2024-08-06T22:04:45.958+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=miguel
AIRFLOW_CTX_DAG_ID=load_parquet_to_bq_dag
AIRFLOW_CTX_TASK_ID=dbt_run
AIRFLOW_CTX_EXECUTION_DATE=2024-08-06T22:04:45.034373+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-06T22:04:45.034373+00:00
[2024-08-06T22:04:45.958+0000] {dbt_hook.py:117} INFO - dbt run --profiles-dir /opt/dbt_project --models load_parquet_to_test
[2024-08-06T22:04:45.964+0000] {dbt_hook.py:126} INFO - Output:
[2024-08-06T22:04:47.232+0000] {dbt_hook.py:130} INFO - [0m22:04:47  Running with dbt=1.8.4
[2024-08-06T22:04:48.041+0000] {dbt_hook.py:130} INFO - [0m22:04:48  Registered adapter: bigquery=1.8.2
[2024-08-06T22:04:48.403+0000] {dbt_hook.py:130} INFO - [0m22:04:48  Found 1 model, 1 source, 473 macros
[2024-08-06T22:04:48.405+0000] {dbt_hook.py:130} INFO - [0m22:04:48
[2024-08-06T22:04:49.712+0000] {dbt_hook.py:130} INFO - [0m22:04:49  Concurrency: 1 threads (target='dev')
[2024-08-06T22:04:49.713+0000] {dbt_hook.py:130} INFO - [0m22:04:49
[2024-08-06T22:04:49.724+0000] {dbt_hook.py:130} INFO - [0m22:04:49  1 of 1 START sql table model prazos_project_dataset.load_parquet_to_test ....... [RUN]
[2024-08-06T22:04:51.080+0000] {dbt_hook.py:130} INFO - [0m22:04:51  BigQuery adapter: https://console.cloud.google.com/bigquery?project=prazos-project&j=bq:US:609b938f-54a9-470a-b53f-69ac2925b756&page=queryresults
[2024-08-06T22:04:51.102+0000] {dbt_hook.py:130} INFO - [0m22:04:51  1 of 1 ERROR creating sql table model prazos_project_dataset.load_parquet_to_test  [[31mERROR[0m in 1.38s]
[2024-08-06T22:04:51.105+0000] {dbt_hook.py:130} INFO - [0m22:04:51
[2024-08-06T22:04:51.106+0000] {dbt_hook.py:130} INFO - [0m22:04:51  Finished running 1 table model in 0 hours 0 minutes and 2.70 seconds (2.70s).
[2024-08-06T22:04:51.234+0000] {dbt_hook.py:130} INFO - [0m22:04:51
[2024-08-06T22:04:51.238+0000] {dbt_hook.py:130} INFO - [0m22:04:51  [31mCompleted with 1 error and 0 warnings:[0m
[2024-08-06T22:04:51.241+0000] {dbt_hook.py:130} INFO - [0m22:04:51
[2024-08-06T22:04:51.246+0000] {dbt_hook.py:130} INFO - [0m22:04:51    Database Error in model load_parquet_to_test (models/load_parquet_to_test.sql)
[2024-08-06T22:04:51.248+0000] {dbt_hook.py:130} INFO -   Syntax error: Expected ")" but got ";" at [15:24]
[2024-08-06T22:04:51.250+0000] {dbt_hook.py:130} INFO -   compiled Code at target/run/prazos_project/models/load_parquet_to_test.sql
[2024-08-06T22:04:51.251+0000] {dbt_hook.py:130} INFO - [0m22:04:51
[2024-08-06T22:04:51.252+0000] {dbt_hook.py:130} INFO - [0m22:04:51  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2024-08-06T22:04:52.521+0000] {dbt_hook.py:132} INFO - Command exited with return code 1
[2024-08-06T22:04:52.569+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/operators/dbt_operator.py", line 98, in execute
    self.create_hook().run_cli('run')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow_dbt/hooks/dbt_hook.py", line 138, in run_cli
    raise AirflowException("dbt command failed")
airflow.exceptions.AirflowException: dbt command failed
[2024-08-06T22:04:52.585+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=load_parquet_to_bq_dag, task_id=dbt_run, execution_date=20240806T220445, start_date=20240806T220445, end_date=20240806T220452
[2024-08-06T22:04:52.614+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 77 for task dbt_run (dbt command failed; 127)
[2024-08-06T22:04:52.645+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-08-06T22:04:52.664+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
